Разметка главной страницы
htmlacademy-htmlcss/1893379-device-33 pull request #2
Opened 2022-01-30 11:45 UTC by Nior21

2022-01-31 07:40 UTC, Manyaka requested changes

2022-01-31 07:40 UTC, Manyaka commented on img/cart_count.svg
> +<svg width="21" height="22" viewBox="0 0 21 22" fill="none" xmlns="http://www.w3.org/2000/svg">
картинки должны быть названы единообразно. Оптимальнее через дефисы, как ниже
https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-03

2022-01-31 07:40 UTC, Manyaka commented on img/quadrocopter.svg
> +<svg width="160" height="160" viewBox="0 0 160 160" fill="none" xmlns="http://www.w3.org/2000/svg">
наведи порядок в папке img. Свегешки отдельно, растр отдельно, хотя бы для начала

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1">
это не используется на этом уровне, так что убери, чтобы страница не скейлилась

2022-01-31 07:40 UTC, Manyaka commented on img/cart_count.svg
> +<svg width="21" height="22" viewBox="0 0 21 22" fill="none" xmlns="http://www.w3.org/2000/svg">
соотв. надо будет везде поменять, и в названиях картинок и в коде

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <img class="logo" src="img\logo.svg" alt="Логотип Device">
```suggestion
    <img class="logo" src="img/logo.svg" alt="Логотип Device.">
```

пути неправильные у картинок - надо везде поправить, и в альтах надо ставить точки на конце для интонационной паузы для скрин-ридеров - тоже поправь везде

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <h1 class="visually-hidden">Device</h1>
Как ты думаешь, зачем этот сайт?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +        <img class="user-navigation search-item seacrh-ico" alt="Поиск">
```suggestion
        <img class="user-navigation search-item search-ico" alt="" src="">
```

src - обязательный атрибут элемента img, так что надо его писать, даже если пустой,
и орфографическая ошибка в слове search - тебе надо поставить проверку орфографии (у тебя ВС кода? там есть такое, русскую и английскую проверку орфографии)

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +        <input class="user-navigation search-item seacrh-input" type="search" placeholder="Текст поиска">
у инпута должен быть обязательный label: https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-05

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      <input class="user-navigation search-item submit-item" type="submit" value="Найти">
это переделай на кнопку, инпутами давно уже никто не пользуется там, где можно использовать кнопки

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <a href="#" class="user-navigation sign-in">Войти</a>
подумай, картинка перед ссылкой на "Войти" - это контентная картинка - она должна быть в виде html тегов, или это декоративная картинка, которую ты потом добавить с помощью псевдоэлементов?

Как думаешь, чем это отличается от поиска? Можно ли на инпут повесить псевдоэлементы?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    </ul>
аналогичный вопрос про контентные и декоративные картинки

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +        <img class="main-navigation-link main-navigation-ico" src="img\catalog-toggler.svg" alt="Каталог">
Почитай требования: https://www.figma.com/file/f8ZtnZcdWC2pSklG1ssm9K/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81?node-id=308%3A470 подумай, какой тег отвечает за этот блок

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <div class="main-navigation-background"></div>
Это что тут будет?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +  <aside class="product-preview">
почему тут aside - расскажи свою логику, пож

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <article class="product-preview-constructor">
тут тоже, почему выбрал article?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      <b class="product-preview-slogan">Порхает как бабочка,<br>жалит как пчела!</b>
```suggestion
      <p class="product-preview-slogan">Порхает как бабочка,<br>жалит как пчела!</p>
```

не надо использовать презентационные теги в html, чтобы разделять сущности: html отвечает за разметку, а за визуал и стили отвечает css

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      </div>
Посмотри в сторону `dl`

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +
надо доделать остальные слайды, их можно взять на странице стайлгайда: https://www.figma.com/file/f8ZtnZcdWC2pSklG1ssm9K/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81?node-id=11549%3A3957

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <!-- Конец блока с breacrumbs -->
это неправильно, так что можешь удалить

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      <img class="product-preview-img" src="img/quadrocopter_with_laser.png">
у картинки есть стрелочки - вперед/назад - надо добавить

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +
у слайдера есть переключатель - точки. Они идут на уровне слайдера, а не одного слайда. Чтобы они заехали на слайд - придется, видимо, использовать позишн абсолют, если не будешь гридом делать, ну в общем, сейчас нужно сделать просто этот блок, который будет под всеми слайдами расположен

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +</header>
и header заканчивается до слайдера

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +  <nav class="site-main-catalog">
слайдер входит в мейн

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +          <h3 class="site-main-catalog-item-title">Виртуальная реальность</h3>
Подумать (посмотреть лайв про картинки), что это - декоративные картинки или контентные. И также, нужны ли тут заголовки - что они озаглавливают?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +          <h3 class="site-main-catalog-item-title">Виртуальная реальность</h3>
соотв. сделать это для всего этого навигационного блока

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <ul class="site-main-benefits-list">
как только пишешь section, то сразу нужен ему заголовок, обычно второго уровня. Если его на дизе нет, то делаешь его вижуали-хидден

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +        <input class="site-main-benefits-button" type=button value="Доставка" action="">
это зачем тут?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      <b class="site-main-benefits-title">Доставка</b>
Мне представляется это заголовком, тем более ниже идет текст, который этот заголовок озаглавливает. Как тебе такая идея?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +        <h3 class="site-main-benefits-title visually-hidden">Доставка</h3>
Это не заголовки - если нечего озаглавливать, то это что-то самостоятельное. Например, это просто текст внутри лишек

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +  </section>
доделать остальные блоки со страницы стайлгайда: https://www.figma.com/file/f8ZtnZcdWC2pSklG1ssm9K/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81?node-id=11558%3A5700

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +        мы неплохо заработаем, поднимая его на ваш этаж./p>
```suggestion
        мы неплохо заработаем, поднимая его на ваш этаж.</p>
```

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +  <section class="site-main-add-offers"></section>
это тут что?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +<footer class="site-footer">
рано футер начал

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +
пропустил блок с рекламным банером - Доставим редкий товар под заказ

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <hr class="site-footer-about">
это не нужно, все презентационные теги не нужны, удобнее для стилизации использовать css

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <hr class="site-footer-contacts">
не нужно

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <p class="site-footer-contacts-content">Вы можете забрать товар сами, заехав в наш офис.<br>Заодно сможете проверить работоспособность покупки.</p>
местами перепутал

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <p class="site-footer-contacts-content">Вы можете забрать товар сами, заехав в наш офис.<br>Заодно сможете проверить работоспособность покупки.</p>
```suggestion
    <p class="site-footer-contacts-content">Вы можете забрать товар сами, заехав в наш офис. Заодно сможете проверить работоспособность покупки.</p>
```

в предыдущих параграфах в аналогичном блоке ты не использовал бры, так что и тут не надо. Ужмешь шириной потом.

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <p class="site-footer-contacts-content">Санкт-Петербург, набережная реки Карповки, 5, литера П.<br>+7 (812) 812-12-12</p>
```suggestion
    <p class="site-footer-contacts-content">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
    +7 (812) 812-12-12
```

сделай телефон через ссылку с телефоном

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <p class="site-footer-contacts-content">пн—пт: с 10:00 до 22:00<br>сб—вс: с 10:00 до 19:00</p>
```suggestion
    <p class="site-footer-contacts-content">пн—пт: с <time>10:00</time> до 22:00<br>сб—вс: с 10:00 до 19:00</p>
       
```

ну и дальше поправь, для времени и дат есть прекрасный тег `time`

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <form class="site-footer-subscription-form">
доделай форму, у неё есть обязательные атрибуты, такие как экшен и метод

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      <input class="site-footer-subscription-button" type="submit" value="Подписаться">
баттон

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      <input class="site-footer-subscription-input" type="email" placeholder="Ваш e-mail">
лейбл

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    </div>
```suggestion
      <p>Это бесплатно</p>
```

объясни почему я оставила только один параграф?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +  <nav class="site-footer-nav">
вот отсюда начинается футер

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +    <section class="site-footer-nav-wrapper site-footer-nav-left-wrapper">
не надо в футере фигачить секции, слишком маленький футер для секционного деления.

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      <img class="site-footer-rectangle" src="" alt="-">
про картинки - смотри все коменты выше. Почему адрес - это ссылка?

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      </ul>
проверь текстовку

2022-01-31 07:40 UTC, Manyaka commented on index.html
> +      <a class="site-footer-nav-telephone" href="tel:78128121212">Тел.: +7 (812) 812-12-12</a>
```suggestion
      <a class="site-footer-nav-telephone" href="tel:+78128121212">Тел.: +7 (812) 812-12-12</a>
```

2022-02-02 09:57 UTC, Nior21 commented on index.html
> +    <div class="main-navigation-background"></div>
На фоне страницы есть желтый блок, который не понятно к какому разделу будет относиться и не понятно как стилизуется. Возможно это просто фон header'а?
Если это так, то мне надо вынести за пределы header'a промо-товары

2022-02-02 10:04 UTC, Manyaka commented on index.html
> +    <div class="main-navigation-background"></div>
а ты их и так вынесешь, там есть комент, где написано, что это не хедер

2022-02-02 10:05 UTC, Manyaka commented on index.html
> +    <div class="main-navigation-background"></div>
щас див удали, когда будешь делать желтый блок и тебе не будет хватать дива, тогда и добавишь

2022-02-02 11:33 UTC, Nior21 commented on index.html
> +
Я по ошибке назвал breadcrumps, не знал что такое "хлебные крошки" от слова совсем. Пока стрелки и точки сделал по свойму используя output и input type="radio". По мере понимания как это делают другие, пойму оставлять текущую схему или нет.

Вынес стрелки до формы, пусть форма отвечает за переключение картинок по реакции на нажатие радио кнопок, которые можно стилизовать по требованиям. А картинку товара уже через абсолют положу между стрелками, где заранее сделаю нужный отступ. То же самое с цифрой 01/02/03, тоже через абсолют.

Фон желтый соответсвенно будет только у header, поэтому все эту промо отправлю в main или если надо могу отдельный раздел сделать, ведь по факту он автономен. Там реклама которая может быть и на любом другом сайте размещена, только вот разметка там с наплывом, поэтому не знаю использовать aside или нет для таких целей? Само содержимое страницы не посвещено конкретно этим товарам из промо, это главная страница, где просто рассказ про компанию и ее товары. По логике промо это нечто побочное, а не мейн. Это так?

2022-02-02 11:41 UTC, Manyaka commented on index.html
> +
сдавай, посмотрю

2022-02-03 14:46 UTC, Manyaka commented on index.html
> +        <img class="user-navigation search-item seacrh-ico" alt="Поиск">
не сделано

2022-02-03 14:48 UTC, Manyaka commented on index.html
> +        <input class="user-navigation search-item seacrh-input" type="search" placeholder="Текст поиска">
пока не сделано

2022-02-03 14:49 UTC, Manyaka commented on index.html
> +    <a href="#" class="user-navigation sign-in">Войти</a>
пока не сделано

2022-02-03 14:50 UTC, Manyaka commented on index.html
> +    </ul>
пока не сделано

2022-02-03 17:20 UTC, Nior21 commented on index.html
> +        <h2 class="site-main-benefits-title visually-hidden">Доставка</h2>
Вот в таком месте как верно создать структуру? Неужели обе строки и заголовок и label оставляем?

2022-02-03 17:29 UTC, Manyaka commented on index.html
> +        <h2 class="site-main-benefits-title visually-hidden">Доставка</h2>
Ты лучше этот комент в код вставь, то место, где тебе не понятно

2022-02-03 19:39 UTC, Nior21 commented on index.html
> +    <a href="#" class="user-navigation sign-in">Войти</a>
Для таких целей используют псевдоэлементы `:before` и `:after` вместе со свойствами
`content: url('path')` или `background-image: url('path')`
Ограничение касается `<input>` и `<img>`, в них эти методы не работают.
Т.к. тут просто ссылка (тег `<a>`), то мы можем не вставлять отдельный тег img

2022-02-03 19:46 UTC, Nior21 commented on index.html
> +    <a href="#" class="user-navigation sign-in">Войти</a>
Пример [тут](https://codepen.io/Nior/pen/wvPWOQm)

2022-02-04 08:43 UTC, Nior21 commented on index.html
> +        <h2 class="site-main-benefits-title visually-hidden">Доставка</h2>
Мы обсудили в телеграмм вопрос, это уже сделано.

2022-02-04 08:58 UTC, Manyaka commented on index.html
> +    <a href="#" class="user-navigation sign-in">Войти</a>
ну вот, ты эти картинки будешь делать псевдо-элементами, поэтому нельзя тут как в поиске использовать `<img>`. В поиске можно было, потому что на инпут псевдики не вешаются.

Так что поправь эти блоки - удали лишний тег <img>

2022-02-04 09:17 UTC, Nior21 commented on index.html
> +        <img class="main-navigation-link main-navigation-ico" src="img\catalog-toggler.svg" alt="Каталог">
Сначала логично было бы подумать что <select>, но не видел селектов которые отображаются в два столбца и более.
Возможно просто баттон и он уже попап (или как он там называется) будет открывать
Сейчас поправлю...

2022-02-04 09:18 UTC, Manyaka commented on index.html
> +        <img class="main-navigation-link main-navigation-ico" src="img\catalog-toggler.svg" alt="Каталог">
да, это кнопка

2022-02-04 17:12 UTC, Nior21 commented on index.html
> +    <a href="#" class="user-navigation sign-in">Войти</a>
Так вроде сделал уже:
[<li class="user-navigation-item">](https://github.com/Nior21/1893379-device-33/blob/0dee4522455f29fef181b133ddc6dc3be7522b30/index.html#L31-L36)

2022-02-04 17:22 UTC, Nior21 commented on index.html
> +    </ul>
Аналогично
https://github.com/Nior21/1893379-device-33/blob/0dee4522455f29fef181b133ddc6dc3be7522b30/index.html#L31-L48

2022-02-04 18:46 UTC, Nior21 commented on index.html
> +        <img class="main-navigation-link main-navigation-ico" src="img\catalog-toggler.svg" alt="Каталог">
Готово. Буду ракету ставить где считаю что выполнил рекомендацию... ну так, для уверенности

2022-02-04 18:50 UTC, Nior21 commented on index.html
> +    <div class="main-navigation-background"></div>
Уже сделано. Див убран

2022-02-04 18:59 UTC, Nior21 commented on index.html
> +  <aside class="product-preview">
Сейчас не на этой строке уже aside, но я пока оставил этот тег, как подходящий в структуру header/main/footer:
1) считаю что промо-продукты не относятся к тому что прямым образом объясняет суть главной страницы, реклама не является ни навигацией, ни объяснением чем занимается компания, в тексте такой информации нет и 2) при этом сам блок не цепляется за майн, в нем нет логической зацепки за дальнейший текст (может мне так показалось), 
3) если же вынести любую карточку с промо-товаром на другую страницу или как рекламу в сайдбар (ну чисто для мысленного эксперимента), то информация ничего не потеряет. Все так же есть завлекающий заголовок, описание и ссылка на оригинальную страницу товара ("подробнее").

2022-02-04 19:03 UTC, Nior21 commented on index.html
> +    <article class="product-preview-constructor">
Article рекомендуется для деления чего-то что похоже по смысловой нагрузке, но отличается так же как отдельные статьи новостей или отдельные сообщения на форуме.
В данном случае есть три отдельных карточки товара, которых может быть и больше и меньше и суть каждой из них не зависит от другой. При этом они все показывают промо-товары.

2022-02-04 19:04 UTC, Nior21 commented on index.html
> +      <b class="product-preview-slogan">Порхает как бабочка,<br>жалит как пчела!</b>
Уже убрал

2022-02-04 19:08 UTC, Nior21 commented on index.html
> +      <img class="product-preview-img" src="img/quadrocopter_with_laser.png">
Вроде добавил. Если все верно, то значит готово

2022-02-07 06:42 UTC, Manyaka commented on index.html
> +      <b class="product-preview-slogan">Порхает как бабочка,<br>жалит как пчела!</b>
Разные теги нужно использовать, потому что в них как раз и заложен смысл, они вообще-то не просто какие-то левые буквы: они сокращения от английских слов, которые обозначают сущность, для которой эти теги сделаны! Верстать разными тегам - это верстать семантично. Ты суп ешь ложкой, а второе - вилкой, а режешь ножом. Ты выучил как пользоваться разными приборами для разной еды, значит и теги выучишь

2022-02-09 07:43 UTC, Nior21 commented on index.html
> +        <input class="site-main-benefits-button" type=button value="Доставка" action="">
Убрал тут заголовки и перенес один h2 в начало section

2022-02-09 07:46 UTC, Nior21 commented on index.html
> +      <b class="site-main-benefits-title">Доставка</b>
Попробовал заменить <b> на <h3>, возможно это хорошая идея.

2022-02-09 07:49 UTC, Nior21 commented on index.html
> +        <h3 class="site-main-benefits-title visually-hidden">Доставка</h3>
Пока поставил заголовки 3 уровня и абзацы.

2022-02-09 07:55 UTC, Nior21 commented on index.html
> +  <section class="site-main-add-offers"></section>
```
<section class="site-main-add-offers">
    <h2 class="site-main-add-offers-title visually-hidden">Доставим редкий товар под заказ</h2>
    <img class="site-main-add-offers-image" src="" alt="Доставка ценных грузов.">
    <p class="site-main-add-offers-content">Доставим редкий товар под заказ</p>
    <img class="site-main-add-offers-more" src="" alt="Узнать подробнее.">
  </section>
```
Вот такая штука должна быть...

2022-02-09 08:01 UTC, Nior21 commented on index.html
> +<footer class="site-footer">
Попробовал исправить. Перенес в main несколько section

2022-02-09 08:42 UTC, Nior21 commented on index.html
> +    <p class="site-footer-contacts-content">пн—пт: с 10:00 до 22:00<br>сб—вс: с 10:00 до 19:00</p>
Не уверен по поводу тега time, но для пробы сделал.
Вообще если я верно понимаю смысл этого тега, то он не помогает в случаях когда мы говорим о каком-то времени каждый день. Он либо показывает конкретную точку во времени, либо некий продолжительный кусок времени.
Мои попытки найти пример как им оформляют время работы организации не увенчались успехом.

2022-02-09 08:52 UTC, Nior21 commented on index.html
> +    </div>
Потому что декоративные изображения мы не вставляем тегами, используем CSS

2022-02-10 05:40 UTC, closed without merging